### ISSUE TITLE
It continues indefinitely

### ISSUE THREAD

**Issue by danolez1** [J3rry320/react-typing-animator#1]
There should be a prop to stop when finished or continue indefinitely. No way to adjust this, have to edit the lib itself.

**Comment by J3rry320** [comment]
Hey I am really sorry. I was AFK for a while. Will push a patch ASAP.

**Comment by J3rry320** [comment]
Fixed the problem in version 5.6.0 
You can pass a prop loop which if set to false will terminate the animation at the last index of the textArray. Needs some style fixing and animation added to the last text apart from that works as intended. Will fix the style issue with some other animation effects in 6.0.0
